import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bite News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="mx-auto max-w-custom bg-white min-h-svh">
          {children}
        </div>
      </body>
    </html>
  );
}
