import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/common/Provider";

export const metadata: Metadata = {
  title: "Bite News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <div className="mx-auto max-w-custom bg-white min-h-svh">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
